apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentmanagement
  labels:
    app: paymentmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentmanagement
  template:
    metadata:
      labels:
        app: paymentmanagement
    spec:
      containers:
        - name: paymentmanagement
          image: skcc12acr.azurecr.io/paymentmanagement:latest
          ports:
            - containerPort: 8080
          env:
            - name: configtext
              valueFrom:
                configMapKeyRef:
                  name: pizzaconfigmap
                  key: key1
